### ISSUE TITLE
Validation support for in-seat transfers

### ISSUE THREAD

**Issue by digitalcora** [mrcagney/gtfs_kit#11]
There is an open GTFS proposal (https://github.com/google/transit/pull/303) to add new `transfer_type` values of 4 and 5 in `transfers.txt` to represent "in-seat" transfers. `gtfs_kit` validation [currently requires](https://github.com/mrcagney/gtfs_kit/blob/c269d65/gtfs_kit/validators.py#L1480) `transfer_type` to be between 0 and 4[^1], which prevents using the proposed value of 5. Not sure what this project's stance on open proposals is, but this does make it slightly more difficult to produce a feed with the new transfer types if you are using `gtfs_kit` validations. I'm currently using a workaround where the feed's `transfers` is temporarily replaced with a copy that doesn't include in-seat transfers before validating it, but then these transfers are not subject to any validation at all.

[^1]: The condition is `in range(5)`, but the endpoint of the range is exclusive: `5 in range(5)` returns `False`.

**Comment by araichev** [comment]
Hi @digitalcora , thanks for the news and clear description of the issue.

Sounds like updating GTFS Kit to support the new transfer type proposal would be relatively quick and easy.
However, i must politely decline the option, because it transcends the current scope of GTFS Kit, namely, to support at most the current official GTFS reference.

That scope is the most sensible and realistic one i can think of, given that i don't have much time and budget for this project at present.

Does that make sense?

**Comment by digitalcora** [comment]
Thanks @araichev. In that case, would it be considered a bug that the current validation allows a `transfer_type` of 4? In the current [GTFS spec](https://developers.google.com/transit/gtfs/reference/#transferstxt), the values only go up to 3.

**Comment by araichev** [comment]
Ah yes, that is a bug indeed.
Fixed now in version 5.2.2.
Thanks @digitalcora .
